//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoopSale
    {
        public string Datum { get; set; }
        public int Butik { get; set; }
        public Nullable<decimal> Koncept_dag { get; set; }
        public Nullable<decimal> Butik_dag { get; set; }
        public Nullable<decimal> Marginalkronor { get; set; }
        public Nullable<decimal> Snittköp { get; set; }
        public Nullable<decimal> Antal_kunder { get; set; }
        public Nullable<decimal> Fys { get; set; }
    }
}
