//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaspberryList
    {
        public string mac { get; set; }
        public string hostname { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<System.DateTime> firstseen { get; set; }
        public Nullable<int> disabled { get; set; }
    }
}
